# pvc-development.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-development
  namespace: development
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi