# pvc-testing.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-testing
  namespace: testing
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi