# pvc-production.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-production
  namespace: production
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi