# pv-production.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-production
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/production"
