wordpressUsername: user
wordpressPassword: user
wordpressEmail: diepeloic31@gmail.com
wordpressBlogName: Development Blog
mariadb:
  enabled: true
  auth:
    rootPassword: ""
    database: bitnami_wordpress
    username: bn_wordpress
    password: ""
resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"
persistence:
  enabled: true
  existingClaim: pvc-development
mariadb:
  primary:
    persistence:
      enabled: true
      existingClaim: pvc-development
