apiVersion: v1
kind: LimitRange
metadata:
  name: test-limits
  namespace: testing
spec:
  limits:
  - default:
      cpu: 1
      memory: 2Gi
    defaultRequest:
      cpu: 200m
      memory: 400Mi
    type: Container
